# Generated by Django 3.1 on 2021-01-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_area_name', models.CharField(max_length=100)),
                ('parking_cost_per_hour', models.IntegerField()),
                ('parking_location', models.CharField(max_length=150)),
                ('parking_facility', models.CharField(choices=[('PR', 'Parking Facility'), ('OS', 'Open Space')], max_length=300)),
                ('security_inclusive', models.BooleanField(default=False)),
                ('carwash_available', models.BooleanField(default=False)),
                ('nearby_restaurant', models.BooleanField(default=False)),
            ],
        ),
    ]
