# Generated by Django 3.1 on 2021-01-30 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='parking_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
