# Generated by Django 3.1 on 2021-01-31 00:00

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210131_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='parking_picture',
            field=models.FileField(null=True, upload_to=mainapp.models.upload_image_path),
        ),
    ]
