# Generated by Django 3.1 on 2021-02-01 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_parking_parking_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_id_no', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone_number', models.CharField(max_length=150)),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.parking')),
            ],
        ),
    ]
