# Generated by Django 3.1 on 2021-02-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_parkingslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='parkingslots',
            name='carwash_available',
        ),
        migrations.RemoveField(
            model_name='parkingslots',
            name='nearby_restaurant',
        ),
        migrations.RemoveField(
            model_name='parkingslots',
            name='parking_area_name',
        ),
        migrations.RemoveField(
            model_name='parkingslots',
            name='parking_cost_per_hour',
        ),
        migrations.RemoveField(
            model_name='parkingslots',
            name='parking_facility',
        ),
        migrations.RemoveField(
            model_name='parkingslots',
            name='parking_location',
        ),
        migrations.RemoveField(
            model_name='parkingslots',
            name='parking_overview',
        ),
        migrations.RemoveField(
            model_name='parkingslots',
            name='security_inclusive',
        ),
        migrations.RemoveField(
            model_name='parkingslots',
            name='slug',
        ),
    ]
