# Generated by Django 3.1 on 2021-02-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210202_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='parking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.parkingslots'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=150)),
                ('manufacture_year', models.CharField(max_length=150)),
                ('vehicle_number_plate', models.CharField(max_length=150)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer')),
            ],
        ),
    ]
