# Generated by Django 3.1 on 2021-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=90, null=True),
        ),
    ]
